export const addressActionTypes = {
  FETCH_STREETS: 'FETCH_STREETS',
  FETCH_STREETS_SUCCESS: 'FETCH_STREETS_SUCCESS',
  FETCH_STREETS_ERROR: 'FETCH_STREETS_ERROR',
  SELECT_STREET: 'SELECT_STREET',
  FETCH_BUILDINGS: 'FETCH_BUILDINGS',
  FETCH_BUILDINGS_SUCCESS: 'FETCH_BUILDINGS_SUCCESS',
  FETCH_BUILDINGS_ERROR: 'FETCH_BUILDINGS_ERROR',
  SELECT_BUILDING: 'SELECT_BUILDING',
}