export const addressActionTypes = {
  FETCH_STREETS: 'FETCH_STREETS',
  FETCH_STREETS_SUCCESS: 'FETCH_STREETS_SUCCESS',
  FETCH_ERROR: 'FETCH_STREETS_ERROR',
  SELECT_STREET: 'SELECT_STREET',
  FETCH_BUILDINGS: 'FETCH_BUILDINGS',
  FETCH_BUILDINGS_SUCCESS: 'FETCH_BUILDINGS_SUCCESS',
  SELECT_BUILDING: 'SELECT_BUILDING',
  FETCH_FLAT: 'FETCH_FLAT',
  FETCH_FLAT_SUCCESS: 'FETCH_FLAT_SUCCESS',
  SELECT_FLAT: 'SELECT_FLAT',
}