export const clientActionTypes = {
  FETCH_CLIENTS: 'FETCH_CLIENTS',
  FETCH_CLIENTS_SUCCESS: 'FETCH_CLIENTS_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  ADD_CLIENT: 'ADD_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  CLIENT_OK: 'CLIENT_OK',
  CLIENT_CANCEL: 'CLIENT_CANCEL',
  CLIENT_ERROR: 'CLIENT_ERROR',
}